### PR TITLE
Pulling Data from WormWiring dataset

### LINKED ISSUE #6: write data pulling functions for the connectomes of interest - xlsx
for the connectomes listed in the readme (roughly, exact ones may change)
- want a simple, clear script to pull necessary graph + metadata from wherever it's hosted online 
- saves that data to the format specified in #1 

Note: Sub-issue of #2 

Specifically, focus on datasets stored as .xlsx files.

### PR DESCRIPTION
**Pull request by pauladkisson**
#### Reference Issues/PRs
Fixes #6 

#### What does this implement/fix? Explain your changes.
This update adds a folder with the relevant wormwiring functions.  The folder contains a file that pulls data from the wormwiring dataset (https://wormwiring.org/), extracts relevant graph and metadata, and outputs a dictionary that maps shortened file names (ex. "syn_adj" for synapse adjacency matrices) to a 2-tuple of lists of graphs (ex. one for male and one for hermaphrodite).  The folder also contains a file that validates the results against the original dataframe, to ensure correctness.

#### Any other comments?
I'm open for suggestions on specific function organization and return format.

### CODE REVIEW

**Review by spencer-loggia — COMMENTED** [review]
Generally this looks good, I've used the code and it works as expected. Not sure if it is supposed to be held to the same style / documentation standard as graspologic, since it's not really being distributed. One thing I would say is maybe include some more comments about the structure of the original excel data, I think that would demystify some aspects of the code. I'll do a more in depth review after having a better idea of what exactly we're looking for.

**Comment by pauladkisson** [comment]
Hey @spencer-loggia, I noticed when I was looking at your graph_io.py file, that your script accepts Networkx Graphs and Digraphs, but one of the connectomes in the wormwiring dataset I have stored as a MultiDigraph.  Does that pose a problem for your function/the spec or is it ok?

**Comment by spencer-loggia** [comment]
> Hey @spencer-loggia, I noticed when I was looking at your graph_io.py file, that your script accepts Networkx Graphs and Digraphs, but one of the connectomes in the wormwiring dataset I have stored as a MultiDigraph. Does that pose a problem for your function/the spec or is it ok?

The spec won't take a nx Multigraph directly, though I did write some code to change a multigraph into a list of graphs. We might actually end up using some other spec, but either way moving between different multigraph representations shouldn't be to hard.

**Comment by spencer-loggia** [comment]
Went through it again, everything is working, I think we can merge it.

**Comment by bdpedigo** [comment]
do you guys have merge power or need me to hit some button?

**Comment by bdpedigo** [comment]
note: consider adding a gitignore, you have a lot of junk files associated with this branch (.ds_store, for instance)

**Comment by bdpedigo** [comment]
(can google "gitignore for python")

**Pull request merged**
